N: 10
ablation: steer
aidevi: false
attribution: false
base: prose
batch_size: 1
batch_start: 0
consistent_ablate: false
data_path: ./data/SOLAR-10.7B-Instruct-v1.0/logits/verse
device: cuda:0
eval_extant: false
eval_model: false
eval_test: false
eval_test_dataset: null
eval_train: false
get_head_reps_for_amir: false
judge_answer_match: false
judge_id: null
max_new_tokens: 256
model_id: upstage/SOLAR-10.7B-Instruct-v1.0
patch_algo: atp
patch_model: true
prompting: false
pyreft: false
seed: 42
skip_existing: false
source: verse
steering: false
vllm: false
